version: "3.8"

services:
  admin:
    image: ${DOCKER_USERNAME}/robot-admin:${ROBOT_VERSION}
    container_name: admin
    ports:
      - "8001:8001"
    devices:
      - "/dev/serial0:/dev/serial0"
    restart: unless-stopped
    stdin_open: true
    tty: true

  calculate-route:
    build:
      context: ./src/robot/calculate-route  # 👈 Build locally on the Pi
    container_name: calculate-route
    volumes:
      - ./images:/app/images
      - /usr/bin/libcamera-jpeg:/usr/bin/libcamera-jpeg
      - /lib/aarch64-linux-gnu:/lib/aarch64-linux-gnu
      - /usr/lib/aarch64-linux-gnu:/usr/lib/aarch64-linux-gnu
    ports:
      - "8000:8000"
    privileged: true
    devices:
      - /dev/vchiq:/dev/vchiq
      - /dev/video0:/dev/video0
      - /dev/media0:/dev/media0
      - /dev/media1:/dev/media1
      - /dev/media2:/dev/media2
      - /dev/media3:/dev/media3
      - /dev/media4:/dev/media4
      - /dev/dri:/dev/dri
    restart: unless-stopped

  log-server:
    image: ${DOCKER_USERNAME}/robot-log-server:latest
    container_name: log-server
    ports:
      - "9000:9000"
    volumes:
      - ./logs:/logs
    restart: unless-stopped