version: "3.8"

services:
  admin:
    image: ${DOCKER_USERNAME}/robot-admin:${ROBOT_VERSION}  # or v1.0.0
    container_name: admin
    ports:
      - "8001:8001"
    devices:
      - "/dev/serial0:/dev/serial0"
    restart: unless-stopped
    stdin_open: true
    tty: true

  calculate-route:
    image: ${DOCKER_USERNAME}/robot-calculate-route:latest  # or v1.0.0
    container_name: calculate-route
    ports:
      - "8000:8000"
    restart: unless-stopped